# Generated by Django 5.2.12 on 2026-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesStor', '0002_alter_infogame_options_alter_infogame_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogame',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
