# Generated by Django 5.2.12 on 2026-04-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesStor', '0003_infogame_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
    ]
